FROM node:23-alpine3.20

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4001

CMD [ "npm", "run", "dev" ]